### ISSUE TITLE
Are the anchors described like [center_x, center_y, w, h]?

### ISSUE THREAD

**Issue by trikim** [foolwood/DaSiamRPN#11]
Excese me, I am confused about the code in 'code/run_SiamRPN.py' at 32 line:
`ori = - (score_size / 2) * total_stride`
I have tested the 'EAO' on VOT2016 and get 0.33. But if changed the code to this:
`ori = - (score_size / 2) * total_stride + total_stride/2`
I have got 0.42 of 'EAO' on VOT2016. Could you explain these for me?

**Comment by foolwood** [comment]
You should run our code with python 2.

Your problem is:
In Python 3: ori = - (score_size / 2) * total_stride =-(17/2)*8=-8.5*8=-68                    (No)
In Python 2: ori = - (score_size / 2) * total_stride =-(17/2)*8=-8*8=-64                       (Yes)
In Python 3: ori = - (score_size / 2) * total_stride + total_stride/2 = -(17/2)*8+4= -64 (Yes)
