### ISSUE TITLE
Can't find code to update the state['window']??

### ISSUE THREAD

**Issue by Alexlastname** [foolwood/DaSiamRPN#24]
First of all, Thanks for your remarkable work!
In my opinion,  the cosine window is applied to suppress bbox shift. It's OK to set its peak in the feature map center at the beginning, but it sounds right to updated its peak to the center of latest bbox after first detection. But I didn't find corresponding code to update it, did I miss something or what?

**Comment by foolwood** [comment]
@Alexlastname 
We follow the convention of visual tracking to use cosine windows. This is a crucial position prior.
Why not update cos window? Since we use a local search strategy by cropping search patches at the last location. So the peak always is located in the center.

Thanks for your question.
