### ISSUE TITLE
Dear foolwood, coula you please release the Train.py please?~

### ISSUE THREAD

**Issue by ZhangSanFengByGit** [foolwood/DaSiamRPN#35]
dear @foolwood ,  I got some problems about SmoothL1 loss in the RPN regression training part,
seems your RPN's region generation is different from that of  the  _Fast-RCNN_ by Kaiming etc. 
yours seems to be pre fixed rather than generating the achors using sliding windows, I'd like to take a close look at the train file to know the correct training method in order to enhance my coding about RPN variant.
BTW, my current work are all about RPN, so this got me curious

**Comment by foolwood** [comment]
Our work is inspired by RPN, so what you want to say is Faster-RCNN?

In common RPN setting, the anchors are fixed? Our [implements](https://github.com/foolwood/DaSiamRPN/blob/167d0dbb38162cf34c74d51c540a492faf3d6e01/code/run_SiamRPN.py#L34) are also a sliding window mode.
```
xx, yy = np.meshgrid([ori + total_stride * dx for dx in range(score_size)],
                         [ori + total_stride * dy for dy in range(score_size)])
xx, yy = np.tile(xx.flatten(), (anchor_num, 1)).flatten(), \
             np.tile(yy.flatten(), (anchor_num, 1)).flatten()
anchor[:, 0], anchor[:, 1] = xx.astype(np.float32), yy.astype(np.float32)
```
What's the different? Our RPN in visual tracking have single scale rather than multi-scale anchor used in detection.

I also want to release the training code. But sadly, it's not allowed by now.

If you still have a question, you can reopen this issue. But for now, I should close it.

P.S. You can also email me (wangqiang2015@ia.ac.cn) to talk more detaills. Maybe you could show the anchors used in detection.
