### ISSUE TITLE
请问开源的代码是不是没有包含论文中NMS的部分

### ISSUE THREAD

**Issue by lj1995513** [foolwood/DaSiamRPN#36]

**Comment by foolwood** [comment]
Our work focuses on **single** object tracking. So we do not use the NMS in this version.

Two of our papers (SiamRPN and DaSiamRPN) talk about NMS.
In SiamRPN, `NMS and select top1` is equal to **argmax**.
```
Non-maximum-suppression (NMS) is performed afterwards
to get the final tracking bounding box. After the final
bounding box is selected, target size is updated by linear
interpolation to keep the shape changing smoothly.
```

In DaSiamRPN, NMS is used to select distractors (this part is removed in all our recent works due to the unstable performance). 
```
the Non Maximum Suppression (NMS) is adopted to select the
potential distractors d_i in each frames.
```

Thanks for your question.
